### ISSUE TITLE
[FEATURE] - Vector layer op basis van geojson input

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-map#153]
**Wat moet er gebeuren**
Mogelijkheid voorzien om naast WMS / GRB en reeds bestaande layers, ook een vector layer toe te voegen aan de map.

**Comment by coemans** [comment]
@pharacyde is het mogelijk om iets meer context/informatie te bezorgen? Ik denk in de eerste plaats aan een code voorbeeld zodat de gewenste API duidelijk wordt.

**Comment by pharacyde** [comment]
Mag afgesloten worden, kan al via de bestaan map layers.
