### ISSUE TITLE
[TASK] - Layers en base layers concept verduidelijken in naamgeving en gebruik

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-map#178]
**Beschrijving**
Het concept van Layers en BaseLayers is recent gewijzigd op niveau van OpenLayers? Momenteel zit het concept als volgt in de kaart component:

``` HTML
<vl-map>
    <vl-map-baselayer-grb-gray></vl-map-baselayer-grb-gray>
    <vl-map-baselayer-grb></vl-map-baselayer-grb>
    <vl-map-baselayer-grb-ortho></vl-map-baselayer-grb-ortho>
    <vl-map-layer data-vl-name="layer" data-vl-features='
        {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [147055.0,197908.0]
                }
            }]
        }'>
    </vl-map-layer>
</vl-map>
```

De vraag werd gesteld om vl-map-layer en vl-map-base-layer op code niveau te laten samensmelten en geen `base` meer te gebruiken in de tag. Base layers kunnen dan aangeduid worden aan de hand van een attribuut `data-vl-base-layer` of een wrapper.

Attribuut:
``` HTML
<vl-map>
    <vl-map-layer-grb-gray data-vl-base-layer></vl-map-layer-grb-gray>
    <vl-map-layer-grb data-vl-base-layer></vl-map-layer-grb>
    <vl-map-layer-grb-ortho data-vl-base-layer></vl-map-layer-grb-ortho>
    <vl-map-layer data-vl-name="layer" data-vl-features='
        {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [147055.0,197908.0]
                }
            }]
        }'>
    </vl-map-layer>
</vl-map>
```

Wrapper:
``` HTML
<vl-map>
    <vl-map-base-layers>
        <vl-map-layer-grb-gray></vl-map-layer-grb-gray>
        <vl-map-layer-grb></vl-map-layer-grb>
        <vl-map-layer-grb-ortho></vl-map-layer-grb-ortho>
    </vl-map-base-layers>
    <vl-map-layer data-vl-name="layer" data-vl-features='
        {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [147055.0,197908.0]
                }
            }]
        }'>
    </vl-map-layer>
</vl-map>
```

Ook op niveau van vl-mapactions zou het concept getOverlayLayers en getBaseLayers vervangen worden door getNonBaseLayers en getBaseLayers aangezien Overlay conceptueel niet hetzelfde is als een Layer en daardoor de naamgeving niet meer correct is.

**Comment by coemans** [comment]
@pascalriquier, @driesva en @pharacyde aangezien deze wijzigingen zouden zorgen voor breaking changes en ze misschien ook niet door iedereen als zinvol beschouwd worden is feedback hierover welkom. Indien nodig kan hierover een overleg ingepland worden.

**Comment by Pieter-Beckers** [comment]
Voor die specifieke gevallen van het GRB zou dit wel nog mogen baseLayer noemen (denk niet dat die anders zouden kunnen gebruikt worden?)

**Comment by driesva** [comment]
De breaking change zou dus enkel een naamswijziging i.c.m. attribuut zijn of wrapper? Het zal dan in de release notes staan, dus geen probleem.

Wat betreft naamgeving toch enkele vragen. Ik ben niet echt vertrouwd met OL dus even rap gekeken. Concepten base layer / overlay houden blijkbaar inderdaad verband met oude versies: http://docs.openlayers.org/library/layers.html#base-layers-and-non-base-layers

In de nieuwe documentatie is er op het eerste zicht niks, het zijn blijkbaar allemaal layers:
https://openlayers.org/en/latest/doc/tutorials/concepts.html

Heeft het dan nog nut om aan onze kant het concept "base layer" vs "non base layer" te behouden?

Kan ook voor verwarring zorgen met OL BaseLayer class https://openlayers.org/en/latest/apidoc/module-ol_layer_Base-BaseLayer.html

Als ze nut hebben dan is een eigen concept zoals "primary layer" oid misschien beter? Of zijn dit altijd GRB layers dus dan misschien "GRB layers" ?

**Comment by pascalriquier** [comment]
nee t verschil tussen "base" layers en "non-base" layers is eigenlijk gewoon maar da ge van het ene er maar 1 zichtbare kunt hebben, en van het andere meerdere
maar hun "BaseLayer" is nu eigenlijk gewoon hun "abstract base class voor alle layers"

**Comment by driesva** [comment]
> nee t verschil tussen "base" layers en "non-base" layers is eigenlijk gewoon maar da ge van het ene er maar 1 zichtbare kunt hebben, en van het andere meerdere

OK 

> maar hun "BaseLayer" is nu eigenlijk gewoon hun "abstract base class voor alle layers"

Ja, vandaar mijn suggestie om geen "base" te gebruiken om verwarring te vermijden... Tenzij dit de gangbare termijn is in het GIS domein...

**Comment by pascalriquier** [comment]
goeie vraag. in de vorige versies gaf je nog met een attribuut aan wat de 'base' layers zijn en wat niet, maar ook dat zie ik niet direct terugkomen bij OL6 ...

**Comment by pascalriquier** [comment]
wat natuurlijk niet betekent dat onze kaart-abstractie wel nog het onderscheid mag maken tussen beide ...

**Comment by pascalriquier** [comment]
ik zie wel z-index van een layer, zou je gewoon daarmee aangeven wat de "onderste" en "bovenste" is?
