### ISSUE TITLE
[FEATURE] - Op topniveau de mini-map niet meer gebruiken om te navigeren

### ISSUE THREAD

**Issue by kevcraey** [milieuinfo/webcomponent-vl-ui-map#181]
**Wat moet er gebeuren**
Als je nu klikt op de vl-map-overview-map om van basislaag te wijzigen wordt de kaart ook gecentreerd naar het punt waarop is geklikt. Dit doet zich enkel voor als de kaart niet gezoomed is. Eenvoudig te reproduceren door in de vl-map-overview-map herhaaldelijk in de hoek te klikken, zo zie je de kaart continue verschuiven.

**Extra info**
- opgemerkt bij testen van UIG-906
- decibel: could have. Gevolgen voor gebruiker zijn beperkt als het zich voordoet (klein beetje pannen) én de situaties waarin het zich voordoet zijn beperkt (enkel als je volledig uitgezoomed bent)

**Comment by coemans** [comment]
Future me (or other person) mini-map = de vl-map-overview-map component.

**Comment by kevcraey** [comment]
present me heeft de verwoording aangepast :)
