### ISSUE TITLE
[FEATURE] - Duidelijk maken dat een kaartlaag niet getoond is omdat die niet beschikbaar is op het zoomniveau

### ISSUE THREAD

**Issue by kevcraey** [milieuinfo/webcomponent-vl-ui-map#182]
**Wat moet er gebeuren**
Momenteel wordt de kaartlaag in de layer-switcher disabled. Voor een gebruiker is het niet duidelijk waarom die kaart als disabled staat. Beter zou zijn dat er een indicatie is die context geeft. Een tekst "niet beschikbaar op dit zoomniveau" of een symbool.

**Extra info**
opgemerkt bij UIG-906
decibel: could have.  Belangrijk om de gebruiker te kunnen informeren maar er zijn eenvoudige workarounds. Bijvoorbeeld in de applicatie weergeven dat sommige kaartlagen maar beschikbaar zijn na inzoomen of een asterix in de naamgeving toevoegen van die kaartlagen met een gelijkaardige uitleg.

**Comment by coemans** [comment]
Interessante opmerking, zet ik op de backlog om intern en/of extern verder te bespreken.

**Comment by coemans** [comment]
Eventueel zouden we kunnen werken met een native (title) of vl tooltip die automatisch (in het Nederlands) toegevoegd wordt en applicatief aangepast kan worden indien nodig (i18n).

**Comment by philipperutten** [comment]
Ter vergelijking: Geopunt.be lost dit probleem niet op.
Er staat wel bij elke kaartlaag een (i) icoontje, wat toegang geeft tot info over de kaartleg ([voorbeeld](https://metadata.vlaanderen.be/metadatacenter/srv/dut/catalog.search#/metadata/7C823055-7BBF-4D62-B55E-F85C30D53162)) incl. schaalbereik.
Maar de gebruiker wordt niet actief geïnformeerd.

**Comment by philipperutten** [comment]
Verder is het ook sterk afhankelijk van de specifieke use case, denk ik, hoe problematisch het is, en hoe actief je de gebruiker moet/wil informeren.

Neem een interne toepassing, die door een handvol domeinexperten dagdagelijks wordt gebruikt: moeten zij in de toepassing er telkens aan herinnerd worden dat een bepaalde kaartlaag pas op een bepaalde schaal weergegeven wordt? Wellicht volstaat het dat hen dat 'offline' een keer wordt verteld; of weten ze dit zelf gewoon al, op basis van hun eigen ervaringen met kaarten.

Ook voor de meeste andere use case geldt denk ik: als een kaartlaag op een bepaald schaalniveau niet weergegeven wordt zal dat in de regel betekenen dat ze op dat niveau voor de gebruiker ook weinig nut zal hebben. Dus zolang ze maar getoond wordt op het schaalniveau dat het voor de gebruiker nut heeft, is er (voor de gebruiker, en dus voor ons) verder misschien ook gewoon helemaal geen probleem.

De onderscheidende factor lijkt me vooral of de kaartlaag zelf het hoofdonderwerp vormt van de use case, of dat ze 'slechts' ondersteunend is aan een andere taak of intentie.

In het laatste geval wil de gebruiker wellicht gewoon zo snel mogelijk doen wat ie moet doen, en zolang de kaartlaag er is op het moment dat het nodig is, is het oké. Hij moet dan verder zo min mogelijk met die kaartlaag bezig zijn, en zo min mogelijk informatie aangereikt krijgen die hem van zijn eigenlijke taak of intentie afleidt.

Pas wanneer "het verkennen van kaartlagen" de kern is van de use case en de gebruiker dus specifiek in de kaartlaag geïnteresseerd is, zal de situatie ontstaan dat de gebruiker de kaart 'mist' en hij daarover geïnformeerd moet worden. Maar ook dan is het weer afhankelijk van de specifieke use case hoe je dat best doet:
- soms zal een algemene boodschap volstaan: "let op, sommige kaartlagen worden pas weergegeven als je ver genoeg inzoomt"
- soms zul je per kaartlaag willen aanmerken of ze op een bepaald moment ('op deze schaal') wel of niet beschikbaar zijn
- en soms zul je de gebruiker heel nadrukkelijk erop willen wijzen dat een bepaalde kaartlaag op dat moment ('op deze schaal') niet beschikbaar is; misschien zelfs met een alert over de kaart heen zodat die echt niet te missen is.

Dat laatste scenario lijkt me eerder uitzonderlijk, en het voorlaatste eigenlijk ook--maar geval per geval te bekijken.

@kevcraey stelt natuurlijk terecht dat het disablen van de kaartlaag geen goede oplossing is: het maakt niet duidelijk wat er aan de hand is, en bovendien beperkt het de gebruiker onnodig (hij zou dan eerst moeten zoomen om de laag af of aan te kunnen zetten). Maar of daar dan een tekstje voor in de plaats moet komen... Ik denk dat dat maar zelden toegevoegde waarde gaat hebben.

**Comment by philipperutten** [comment]
Bovendien, als de use case inderdaad is "het verkennen van een of meerdere kaartlagen", moeten we ons sowieso al de vraag stellen of wij daar überhaupt iets voor moeten zitten bouwen, of dat we in dat geval niet gewoon beter Geopunt gebruiken.

**Comment by philipperutten** [comment]
> Ik denk dat als een gebruiker zoals bij Geopunt.be een kaartlaag aanzet en geen resultaat ziet eerder het gevoel heeft dat de kaart niet werkt of de kaart werkt maar er geen data beschikbaar is.

Dat ligt er maar aan wat de gebruiker verwacht. Een expert-gebruiker zal wel weten hoe het werkt. Een burger daarentegen zal dat idd kunnen denken. M.i. dus echt geval per geval te bekijken.

> In het geval van bijvoorbeeld overstromingsgevoelige gebieden kan hierdoor het probleem ontstaan dat de gebruiker de kaartlaag aanzet en geen overstromingsgevoelige gebieden ziet dus concludeert dat er geen zijn. Het lijkt me dan veiliger om de kaartlaag op de niet beschikbare resoluties niet beschikbaar te maken. De gebruiker heeft dan niet de mogelijkheid om de overstromingsgevoelige gebieden kaart aan te zetten en kan zich de vraag stellen hoe dat komt, maar zal geen foute conclusies trekken over het al dan niet aanwezig zijn van overstromingsgevoelige gebieden op de huidige resolutie.

Inderdaad wil je voorkomen dat mensen in zo'n geval verkeerde conclusies trekken, maar de oplossing lijkt me dan eerder te liggen in heldere waarschuwing/toelichting dan in belemmering.

> [indien applicatief een oplossing voorzien wordt wanneer nodig] bestaat het gevaar dat iedereen applicatief een andere oplossing voorziet en dit over applicaties heen verwarrend kan zijn voor de eindgebruiker.

Ik zou daarom een paar vaste patronen bepalen, waaruit geval per geval gekozen wordt. Ik denk dan zoals in eerdere opmerking aan:
- een algemene waarschuwing (alert)
- een indicatie per kaartlaag of ze zichtbaar is op het betreffende schaalniveau (warningicoon+tooltip/overlay?)
- een in het oog springende waarschuwing (over de kaart heen?) wanneer een belangrijke kaartlaag niet wordt weergegeven
- eventueel een combinatie

...maar dus enkel toe te passen wanneer de use case daar echt om vraagt, dwz als er daadwerkelijk een probleem of risico is.

**Comment by coemans** [comment]
@philipperutten lijkt me prima om die patronen te voorzien op vraag, al dan niet gecentraliseerd. @kevcraey aan jou om verder te oordelen of de use case vraagt om één van deze patronen en van daaruit zien we verder of we al iets centraal moeten voorzien of het eerder thuis hoort in de applicatie.

**Comment by coemans** [comment]
Voorlopig blijkt het niet nodig te zijn om centraal een generieke oplossing te voorzien, anders vernemen we het graag.
