### ISSUE TITLE
[FEATURE] - proj4.js niet meer laden als script 

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-map#189]
**Wat moet er gebeuren**
Bekijken of proj4.js ook via _import_ geladen kan worden in plaats van in te laden via script.

Nu staat er in vl-map-all.js :
```JS
Promise.all([
  awaitScript('vl-map-proj4', '/node_modules/proj4/dist/proj4.js'),
]).then(() => {
  define('vl-map', VlMap);
```
Dit zorgde ervoor dat we in onze huidige Polymer build dit als extra dependency moesten opgeven.

**Comment by coemans** [comment]
Laden is momenteel nog steeds via `awaitScript` maar steeds via node_modules waardoor er applicatief geen aanpassingen nodig zijn.

**Comment by driesva** [comment]
> Laden is momenteel nog steeds via `awaitScript` maar steeds via node_modules waardoor er applicatief geen aanpassingen nodig zijn.

Nog niet getest, maar na communicatie meen ik te begrijpen dat we dit nog expliciet mee moeten bundelen. Dus in ons geval moeten blijven we via de [Webpack copy plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) volgende config hebben:

```
        new CopyWebpackPlugin({
            patterns: [
                 {
                     from: 'node_modules/proj4/dist/proj4.js',
                     to: 'node_modules/proj4/dist/proj4.js'
                 },
```

De fix zal wel het probleem oplossen waarbij er gezocht werd naar '/proj4/dist/proj4.js' (ipv 'node_modules/proj4/dist/proj4.js').

De feature request was om  `import` te gebruiken, dus vandaar _reopen_.
