### ISSUE TITLE
[BUG] - race conditie zorgt ervoor dat map layer action niet altijd geactiveerd wordt

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-map#190]
**Omschrijf het probleem**
Na de upgrade van onze applicatie was een feature vaak niet selecteerbaar bij het openen van de applicatie. Meermaals herladen was de enige optie om het werkend te krijgen. Het lijkt om een race conditie bij het activeren van een actie te gaan.

**Hoe te reproduceren**
In onze applicatie hebben we een _select action_ die programmatisch wordt vervolledigd en geactiveerd.

Declaratie:
```
<vl-map-select-action data-vl-cluster></vl-map-select-action>
```

Initialisatie:
```
    action.layer = this._kaartlaag.layer;
    action.style = this._maakClusterStijl;
    action.onSelect(this._clusterOnSelectCallback);
    action.activate();
```

Na wat debugging heb ik gevonden dat in vl-map-layer-action.js het volgende gebeurt bij het zetten van een layer:
```
  set layer(layer) {
    this._layer = layer;
    this._processAction();
  }

// ...

  _processAction() {
    this._mapElement.ready.then(() => {
      if (this._action) {
        this._mapElement.removeAction(this._action);
      }

      if (this.layer) {
        this._action = this._createAction(this.layer);
        super._processAction();
      }
    });
  }
```
De __action_ wordt pas gemaakt na het zetten van de layer wanneer het map element _ready_ is.

In vl-map-action.js zal het aanroepen van _activate_ resulteren in het aanroepen van de map om de actie te activeren
```
  activate() {
    this._mapElement.activateAction(this.action);
  }
```

In vl-map.js:
```
  activateAction(action) {
    if (action) {
      this.map.activateAction(action);
      this.dispatchEvent(new Event(VlMap.EVENTS.action.activated));
    }
  }
```

Het probleem is dus als bij het zetten van de layer, de interne __action_ niet tijdig werd gemaakt, deze nog _undefined_ is wanneer de activatie plaatsvindt. Uiteindelijk gebeurt er dan niks bij activatie...

Een workaround werd gevonden door in onze code expliciet te wachten tot de action bestaat na het zetten van de layer:
```
    awaitUntil(() => action.action).then(() => {
      action.activate();
    });
```

**Gewenst gedrag**
Dat deze zaken intern in de webcomponent worden afgehandeld en dus een feature altijd selecteerbaar is na activatie.

**Omgeving (gelieve aan te vullen):**
 - Browser _any_
 - Versie component 5.0.1

**Extra info**
Misschien kunnen sommige zaken meer declaratief in onze applicatie, maar dit is hoe de applicatie destijds werd gemaakt.

**Comment by kevcraey** [comment]
ticket aangemaakt
