### ISSUE TITLE
[BUG] - vl-select in combinatie met vl-map-search toont verkeerde keuze tekst

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-map#191]
**Omschrijf het probleem**
In onze applicatie hebben we op een plaats een vl-map-search en op een andere plaats een vl-select. Per toeval heb ik opgemerkt dat de tekst voor het zoeken in de vl-select, degene was van de vl-map-search.

**Hoe te reproduceren**
Ik heb het ook kunnen reproduceren door aan de demo pagina van de vl-map-search het volgende toe te voegen:
```
    <div class="demo">
      <select is="vl-select" tabindex="0"
              disabled
              data-vl-select
              data-vl-select-search-empty-text="Geen test gevonden">
          <option placeholder value="">Kies een test</option>

          <option value="test1" selected>test 1</option>
          <option value="test2">test2</option>
          <option value="test3">test3</option>
      </select>
    </div>
```

**Screenshots**
Soms wordt dan het volgende getoond:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/29454303/103344585-4e567600-4a8f-11eb-8436-deae40bc7e68.png">
"Gemeente, straat en huisnummer" is daar total irrelevant.

Wat het moet zijn is:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/29454303/103344632-6d550800-4a8f-11eb-87bb-cd9d19a1a966.png">

Tot op heden kon ik het enkel in Firefox reproduceren op de demo pagina. Het treedt daar niet systematisch op, maar van tijd tot tijd gaat het dus fout. 

In onze applicatie gaat het ook mis met Edge, Chrome en Safari:

![image](https://user-images.githubusercontent.com/29454303/103345361-7e9f1400-4a91-11eb-998a-035d89d66c4a.png)

**Omgeving:**
 - Browser _any_
 - Versie component vl-ui-select 4.1.7 en vl-ui-map 5.0.1

**Comment by coemans** [comment]
Probleem zou ondertussen opgelost moeten zijn in recentere versies. Indien niet het geval, kan issue opnieuw geopend worden.

**Comment by driesva** [comment]
Nog eens nagekeken in onze applicatie en het probleem lijkt zich inderdaad niet meer voor te doen sinds recente web componenten update 👍
