### ISSUE TITLE
[BUG] - vl-map-search samen met layer-switcher zorgt ervoor dat de componenten boven elkaar komen

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-map#197]
**Omschrijf het probleem**
Indien zowel de Map Search component als de Map Side Sheet wordt gebruikt, komen die over elkaar (zie screenshot).

**Hoe te reproduceren**
Een vl-map component met hierin een vl-map-search en een vl-map-side-sheet met bijvoorbeeld een vl-map-layer-switcher.

`<vl-map>
  <vl-map-search></vl-map-search>
  <vl-map-side-sheet>
    <vl-map-layer-switcher></vl-map-layer-switcher>
  </vl-map-side-sheet>
</vl-map>`

**Gewenst gedrag**
De map side sheet zou kunnen detecteren dat er al een vl-map-search is en meer naar onder moeten komen dan.

**Screenshots**`
![image](https://user-images.githubusercontent.com/28813026/105704828-aad27700-5f0f-11eb-9e83-d58292c43850.png)

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome
 - Versie: 88.0.4324.96
 - Versie component: 5.1.0

**Extra info**
Extra context omtrent het probleem.

**Comment by Rubenth** [comment]
I.v.m. het gewenst gedrag hier, is het eventueel ook een optie om deze in de rechterbovenhoek te plaatsen op de kaart?

**Comment by Pieter-Beckers** [comment]
Dat dacht ik ook eerst, maar Tom stelde voor om het meer naar onder te plaatsen. Eventueel kan de optie ingebouwd worden om het toch rechts te plaatsen (dit is wellicht enkel de property naar de side sheet doorgeven, waar die al bestaat).

**Comment by Rubenth** [comment]
Ja Tom had het inderdaad ook net mondeling toegelicht. Ik begrijp niet hoe die property naar de side sheet zou doorgegeven moeten worden? Die vl-map-search staat toch los van deze? Of bedoel je ivm het gewenst gedrag dat in jouw oorspronkelijke issue staat?

**Comment by Pieter-Beckers** [comment]
Ja, naar de layer-switcher bedoel ik dan

**Comment by pascalriquier** [comment]
@kspeltix deze is nog steeds een issue. We kunnen hier voorlopig wel rond met wat custom JS maar graag een oplossing. Vermoedelijk relatief positioneren van alle elementen op die kaart ipv absolute.
