### ISSUE TITLE
[BUG] - Volgorde van basislagen in de configuratie vl-map zouden ook de volgorde moeten zijn zoals ze getoond worden

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-map#199]
**Omschrijf het probleem**
Als ik verschillende soorten basislagen mix, dus bvb vl-map-baselayer en vl-map-baselayer-grb-ortho, zal de ortho baselayer altijd laatst getoond worden, zelfs al zet ik deze eerst in de configuratie van de vl-map.

**Hoe te reproduceren**

`<vl-map>
<vl-map-overview-map></vl-map-overview-map>
<vl-map-baselayer-grb-ortho></vl-map-baselayer-grb-ortho>
<vl-map-baselayer data-vl-type="wmts" data-vl-url="https://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts" data-vl-layer="grb_bsk" data-vl-title="GRB-Basiskaart"></vl-map-baselayer>
</vl-map>`

**Gewenst gedrag**
De volgorde waarin de baselayer gedefinieerd zijn, zou ook de volgorde moeten zijn waarin ze getoond worden. Dus specifiek in bovenstaand geval zou dit de GRB-Basiskaart moeten zijn.

**Screenshots**

De GRB basiskaart wordt foutief eerst getoond met bovenstaande configuratie:

![image](https://user-images.githubusercontent.com/28813026/105707330-0eaa6f00-5f13-11eb-9b14-0d49fe2a3e6e.png)

**Omgeving (gelieve aan te vullen):**
 - Browser: chrome
- Versie: 88.0.4324.96
- Versie component: 5.1.0

**Extra info**
- Workaround: alles definiëren als vl-map-baselayer met manuele configuratie

**Comment by kevcraey** [comment]
ticket aangemaakt
