### ISSUE TITLE
[BUG] - Zoeken met hyphen-minus '-' werkt niet altijd

### ISSUE THREAD

**Issue by stefanborghys** [milieuinfo/webcomponent-vl-ui-map#211]
**Omschrijf het probleem**
Bij het zoeken op de kaart is het '-' karakter niet altijd bruikbaar.

**Hoe te reproduceren**
Als ik via de demo pagina: https://webcomponenten.omgeving.vlaanderen.be/demo/vl-map-search.html
gebruik maak van het voorbeeld: "Kaart met adres zoek functionaliteit" 
en zoek op 'Sint-', verschijnt het '-' karakter niet.

<img width="1440" alt="afbeelding" src="https://user-images.githubusercontent.com/1375279/106934546-87cb7280-671a-11eb-80d9-8f385d3bb9ac.png">

Als ik gebruik maak van het voorbeeld: "Handmatige koppeling afzonderlijke adres zoek functionaliteit
en zoek op "Sint-', verschijnt het '-' karakter wel.
<img width="1435" alt="afbeelding" src="https://user-images.githubusercontent.com/1375279/106934955-12ac6d00-671b-11eb-8238-35c58337373c.png">

**Gewenst gedrag**
Ik wil altijd kunnen zoeken d.m.v. '-'.

**Omgeving:**
 - Browser: Firefox 
 - Versie 85.0 (64-bits)
 - Versie component 5.1.0

**Comment by coemans** [comment]
Eventuele oplossing via #225.

**Comment by kevcraey** [comment]
ticket aangemaakt
