### ISSUE TITLE
[BUG] - Combineren van vl-map-side-sheet met de vl-map zorgt voor discrepantie bij het zoomen op de kaart

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-map#212]
**Wat moet er gebeuren**

In sommige toepassing zal de side sheet (bijna) altijd open staan. Hierdoor is permanent een deel van de map verborgen onder de side-sheet. In combinatie met het zoom-to-extent attribuut, wil dit zeggen dat een deel van het gebied waar de gebruiker in geïnteresseerd is verborgen is onder die side-sheet.

Een openstaande side-sheet moet dus kunnen gecombineerd worden met zoom-to-extent op een manier die handig is voor de gebruiker. Ofwel door zoom-to-extent rekening te laten houden met het verborgen deel van de kaart, ofwel door de side-sheet naast de kaart te plaatsen (of mogelijks nog andere oplossing).

**Comment by kevcraey** [comment]
bestaat al UIG ticket voor
