### ISSUE TITLE
[FEATURE] - VlMapSearch: Tekst "Lokaliseer adres" is te eng geworden

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-map#214]
**Wat moet er gebeuren**
In de VlMapSearch component wordt standaard de placeholder "Lokaliseer adres" gebruikt. Nu er ook op coördinaat kan gezocht worden, lijkt het beter om de standaard waarde te veranderen naar bvb: 'Zoeken op adres of coördinaat'

**Extra info**
Extra info, indien nodig.

**Comment by coemans** [comment]
De zoek placeholder is ondertussen "Zoeken op adres of coördinaat" en kan overschreven worden via het attribuut `data-vl-search-placeholder`. De algemene placeholder kan overschreven worden via `data-vl-placeholder` de standaard tekst is "Lokaliseer adres" en kan beter aangepast worden naar "Zoek op kaart". Dit zal binnenkort uitgevoerd worden.
