### ISSUE TITLE
[BUG] - VlMapSearch: Tekst van 'searchPlaceholder' komt er niet volledig op

### ISSUE THREAD

**Issue by Pieter-Beckers** [milieuinfo/webcomponent-vl-ui-map#215]
**Omschrijf het probleem**
Bij de VlMapSearch rechtstreeks op een kaart wordt de placeholder tekst van het zoeken niet volledig getoond bij bepaalde schermbreedtes (boven 766px lijkt het er niet volledig op te komen)

**Hoe te reproduceren**
=> /demo/vl-map-search.html 
=> 1ste demo: Kaart met adres zoek functionaliteit
=> Maak breedte van scherm groter dan 766px
=> klikken op 'Lokaliseer adres'

=> Er komt: 'Gemeente, straat en huisnummer of Lam'

**Gewenst gedrag**
Ofwel tekst korter maken default ofwel op een tweede lijn laten komen

**Screenshots**
Indien mogelijk, voeg hier screenshots/logs/videos toe

**Omgeving (gelieve aan te vullen):**
 - Browser [vb. chrome, safari]
 - Versie [vb. 22]
 - Versie component [vb. 1.0.14]

**Extra info**
Extra context omtrent het probleem.

**Comment by coemans** [comment]
Ik stel volgende default placeholder voor: "Zoek op adres of coördinaat", eventueel kan later de functionaliteit toegevoegd worden om dit te overschrijven.

<img width="2560" alt="placeholder" src="https://user-images.githubusercontent.com/11139249/107387355-05b1c400-6af5-11eb-90e7-9905e98d5db1.png">

@philipperutten ter info.
