### ISSUE TITLE
[BUG] - [map-layer-switcher] volgende layer kiezen verschuift de kaart

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-map#223]
**Omschrijf het probleem**
Wanneer je de volgende layer kiest in de layer-switcher, verschuift je kaart telkens tot hij niet meer verder kan. 

**EDIT**: 
De layer-switcher doet 2 zaken tegelijkertijd. Namelijk de laag veranderen, maar ook de kaart verschuiven naar de locatie waarop je geklikt heb in het overzichtskaartje zelf. (Opgemerkt door @driesva )

**Hoe te reproduceren**
Ga naar de demo-pagina en blijf enkele keren klikken op de layer-switcher https://webcomponenten.omgeving.vlaanderen.be/demo/vl-map-overview-map.html 

**Gewenst gedrag**
Dat de kaart blijft staan.

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome

**Comment by coemans** [comment]
Duplicatie #181.
