### ISSUE TITLE
[FEATURE] - 

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-map#225]
**Wat moet er gebeuren**
Indien mogelijk volgende interacties default aan of af kunnen zetten op de kaart
* ol.interaction.PinchZoom
* ol.interaction.PinchRotate
* ol.interaction.MouseWheelZoom (is er al)
* ol.interaction.KeyboardZoom
* ol.interaction.KeyboardPan
* ol.interaction.DoubleClickZoom

**Extra info**
vooral de keyboard zoom is nu belangrijk daar die op de + en - keydown events luistert en het dus niet mogelijk maakt om deze in de vl-map-search te tippen. -> Sint-Pieters-Leeuw opzoeken gaat dus niet.

**Comment by kevcraey** [comment]
ticket aangemaakt
