### ISSUE TITLE
[BUG] - niet default-active action wordt actief na drukken op escape toets.

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-map#229]
**Omschrijf het probleem**
Wanneer er geen default-active acties zijn, wordt de eerste geselecteerd om active te zijn na indrukken van de esc toets.

De esc toets activeert zogezegd de default actie, maar er is geen default actie dus moet die ook niet geactiveerd worden.

**Hoe te reproduceren**
Laat `data-vl-default-active` weg op map action en druk esc terwijl op de map.

**Gewenst gedrag**
Actie wordt niet actief indien niet de default

**Comment by kevcraey** [comment]
bestaat al UIG ticket voor
