### ISSUE TITLE
[FEATURE] - data-vl-visible attribuut voor vl-map-layer

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-map#236]
**Wat moet er gebeuren**
We willen een attribuut, data-vl-visible, op de vl-map-layer. 

Momenteel is iedere layer zichtbaar, wat niet altijd de bedoeling is.

**Comment by coemans** [comment]
Hiervoor kan nu het attribuut `data-vl-hidden` gebruikt worden.
