### ISSUE TITLE
[TASK] - VlMapDrawPolygonAction test component kan niet overweg met coordinaten verschillend van pixels

### ISSUE THREAD

**Issue by stefanborghys** [milieuinfo/webcomponent-vl-ui-map#240]
**Beschrijving**
De 'VlMapDrawPolygonAction' test component, bevat een method draw(coorinates).
Deze verwacht als rest params pixel coordinaten. Het zou handig zijn dit uit te breiden of om te zetten naar gewone en lambert coordinaten als input. Als afnemer / gebruiker lijkt dit me interessant want ik test mijn scenarios met zulke coordinaten in het achterhoofd en niet met pixels. 

Voorlopig heb ik dit opgelost door op de 'VlMap' test component, de private methode '_getPixelFromCoordinate(coordinates)' aan te roepen. Merk ook op, de vermelde methodes hebben als input de benaming 'coordinates' maar dit begrip lijkt dus niet eenduidig. Ik ging namelijk uit van lambert coordinaten. Terwijl de ene exclusief pixels verwacht en de andere ... andere coordinaten. Miss is het dus ook wel interessant de benaming duidelijker te stellen of documenteren.

**Extra info**
Gerelateerd aan: https://www.milieuinfo.be/jira/browse/VOORTOETS-3533

**Comment by stefanborghys** [comment]
@SanderKleykens @pascalriquier @Pieter-Beckers @wautergu wat vinden jullie van dit voorstel?

**Comment by SanderKleykens** [comment]
Een draw die lambert coordinaten verwacht lijkt me zelf prima. Een alternatief is de _getPixelFromCoordinates public maken en de 2 combineren waar nodig. Dat laatste is misschien wat flexibeler en 'bloat' de API minder, ten koste van gebruikersgemak.

Een argument hernoemen om duidelijker te weerspiegelen wat meegegeven moet worden, kan enkel maar voordelen hebben. Dus doe gerust denk ik dan :)

**Comment by pascalriquier** [comment]
Duidelijkheid is altijd beter. Ik ben zeker geen voorstander van "the usual Javascript way" gooi maar een object er naartoe en de methode zal wel uitvogelen wat je bedoelt. Dan heb ik liever dat het in de methode naam zit.

**Comment by coemans** [comment]
Als afnemers steeds met Lambert coördinaten gaan werken, wat me logisch lijkt, denk ik dat de publieke methode geen pixel coordinaten moet kunnen ontvangen. In dat geval kan er intern wat logica aangepast worden en moeten de e2e testen van de vl-map webcomponent ook Lambert coördinaten gebruiken.
