### ISSUE TITLE
[TASK] - Placeholder in vl-map-search aanpassen

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-map#86]
**Beschrijving**
vl-map-search heeft een placeholder "Zoek item".
Zo verwacht iets informatieve, vb: "Zoek gemeente, straat..."

**Comment by driesva** [comment]
Dit moet niet enkel zijn wanneer de select wordt aangeklikt maar reeds bij het tonen van het tekstveld. Vb in onze applicatie zie je nu:
![image](https://user-images.githubusercontent.com/29454303/68187970-62e0d080-ffa8-11e9-9b0f-f2e1452fa50b.png)
Maar voor de gebruiker is het totaal niet duidelijk wat die select doet. We zouden een label kunnen toevoegen maar op mobile is dat plaatsverspilling.

De default tekst bij openklappen "Geen resterende opties gevonden" is ook irrelevant.

**Comment by coemans** [comment]
Duplicatie van https://github.com/milieuinfo/webcomponent-vl-ui-select/issues/23. Issue zal ik open houden, maar beperkt zich tot upgrade van vl-ui-select webcomponent.

**Comment by ZhaodiFengVlaanderen** [comment]
> Duplicatie van [milieuinfo/webcomponent-vl-ui-select#23](https://github.com/milieuinfo/webcomponent-vl-ui-select/issues/23). Issue zal ik open houden, maar beperkt zich tot upgrade van vl-ui-select webcomponent.

Ik denk de placeholder moet ook aangepaste worden in vl-map-search zelf. Want er is geen slot voorzien voor de vl-select.
