### ISSUE TITLE
[BUG] - klikken op feature werkt niet altijd op mobile

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-map#87]
**Omschrijf het probleem**
Wanneer je de kaart op smartphone bekijkt en je klikt op een feature gebeurt er vaak niks

**Hoe te reproduceren**
Een kaart met features mobiel bekijken

`code snippet`

**Gewenst gedrag**
click event dat gecapteerd wordt

**Omgeving (gelieve aan te vullen):**
 - Browser mobile chrome op Android

**Extra info**
Vermoedelijk heeft dit met een gekend probleem met openlayers te maken. Echter OL heeft hiervoor een oplossing: https://openlayers.org/en/latest/examples/hit-tolerance.html

Helaas is de versie van open layers die we gebruiken ( Version: v3.13.1) volledig outdated, de release dateert van  Feb 4, 2016 (https://github.com/openlayers/openlayers/releases/tag/v3.13.1) waardoor we die functionaliteit niet kunnen gebruiken...

**Comment by coemans** [comment]
Oplossing kan dan inderdaad een upgrade van OL zijn. Tot op vandaag hadden we functioneel geen reden om de upgrade uit te voeren, waardoor deze in kader van een project nooit is uitgevoerd.

**Comment by driesva** [comment]
OK, ik zal eens proberen of de upgrade straightforward is.

**Comment by coemans** [comment]
De wijzigingen zullen voornamelijk in https://github.com/milieuinfo/vl-mapactions moeten gebeuren. We staan enkele major versies achter, dus vermoedelijk zijn er wel wat breaking changes gebeurd. We hebben het voordeel dat we kunnen terugvallen op heel wat unit testen, dus we kunnen met een gerust hard een upgrade uitvoeren.

Als ik kan ondersteunen, laat je het me maar weten!

**Comment by driesva** [comment]
Huidige status:
- branch  "ol-upgrade" gemaakt voor vl-mapactions waarin upgrade werd gedaan naar OL 6.1.1 Op dezelfde manier als huidig gebruik (dus commit van dist + src en geen npm install). **Er zijn nog 6 falende testen** Deze gebruiken spies waardoor ze vaak gericht zijn om de implementatie. Nog te onderzoeken of het probleem de test is of er een regressie is.

  - code weggedaan die zoom, overview map, ... op andere plaats zet, niet meer nodig met huidige versie
  - defaultDataProjection hernoemt
- branch "ol-upgrade" gemaakt voor vl-ui-map en de branch van vl-mapactions gebruikt.
  - testen gefikst waarbij de fout meestal aan de test zelf lag
  - hernoemen defaultDataProjection
  - workaround voor issue met ScaleLine (iemand met meer kennis van zaken zal dit moeten valideren)
  - deze branch reeds gemerged in VHRMVC-70 zodat we de functionaliteit voor mobile al kunnen gebruiken.

De testen op zich zijn lang niet voldoende om regressies te vinden. Intensief manueel testen zal nodig zijn.

**Comment by driesva** [comment]
Testen in vl-mapactions gecorrigeerd. Daarbij zijn volgende dingen aan het licht gekomen:
- nieuwe en lege MultiPolygon moet als volgt worden gemaakt new `ol.geom.MultiPolygon([])`
- _unByKey_ zit nu in volgende package: `ol.Observable.unByKey`

**Comment by driesva** [comment]
Enige minor issue waarvan ik weet heb, is dat de layout van zoom slider op mobile niet volledig correct is. Aangezien mobile geen prioriteit meer is voor ons, zal ik hiervoor een aparte bug maken.

Voor de rest lijkt alles wat ik getest heb te werken. Echter gezien de vele customizations in map-actions zullen de afnemers grondig moeten testen over geen regressies zijn.

**Comment by coemans** [comment]
Kan/mag ik besluiten dat de upgrade van OL, die in kader van dit ticket speciaal voor mobile gebeurd is, dan ook niet meer dringend is voor jullie? Het geïnvesteerde werk kunnen we natuurlijk wel recupereren om de upgrade an sich te doen, maar gezien de kans op ongewenste neveneffecten stel ik dit liever uit tot de kaart meer functionaliteit bevat die via end2end testen gedekt zijn.

**Comment by driesva** [comment]
Ja en nee. Wat we reeds hebben willen we afwerken. Als er nieuwe issues opduiken voor mobile hebben die momenteel geen prioriteit.

De nieuwe map wordt reeds gebruikt in de toepassing, dus ook op desktop. Ik doe liever geen rollback.

Code wijzigingen waar minimaal, dus veel valt er niet te reviewen. De vraag is echter in hoeverre de applicaties die deze component afnemen, openlayers specifieke functionaliteit gebruiken (waarbij er breaking changes waren).

**Comment by coemans** [comment]
De OL specifieke functionaliteit in de applicaties is geen probleem, ze zijn namelijk niet verplicht om de upgrade uit te voeren.

Ik zet de review en het verwerken van de PR op de planning.
