### ISSUE TITLE
[BUG] - vl-map-search werkt niet in mobile Safari

### ISSUE THREAD

**Issue by johanbuntinx** [milieuinfo/webcomponent-vl-ui-map#88]
**Omschrijf het probleem**
Mobile Safari toont een lege dropdown en er kan niet in getypt worden

**Hoe te reproduceren**
Open de demo pagina: https://webcomponenten.omgeving.vlaanderen.be/demo/vl-map-search.html

**Gewenst gedrag**
Licht kort en duidelijk toe wat het gewenst gedrag is.

**Screenshots**
![IMG_20191106_092243101](https://user-images.githubusercontent.com/4756674/68282361-d56db100-0079-11ea-9803-8e0472a6d005.jpg)

**Omgeving (gelieve aan te vullen):**
 - Browser Safari mobile
 - Versie 13
 - Versie component [vb. 1.0.14]

**Extra info**
Extra context omtrent het probleem.

**Comment by coemans** [comment]
@johanbuntinx probleem is ook reproduceerbaar in (niet mobile) Safari. Ik heb het probleem gevonden, ik probeer vandaag nog de bug fix te releasen.

**Comment by coemans** [comment]
@johanbuntinx ik heb alvast een branch (88-vl-map-search-safari-rendering-probleem) voorzien die het rendering probleem in Safari oplost. Er lijkt wel nog iets fout te lopen bij het renderen van de zoekresultaten in Safari. Hier heb ik nog niet naar kunnen kijken.
