### ISSUE TITLE
[BUG] - vl-map-search niet WCAG compliant

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-map#96]
**Omschrijf het probleem**
De map search gebruikt een _select_ zonder label. Te bekijken in context of WCAG of hier geen `aria-label` attribuut moet komen aangezien er precies nergens anders een label wordt gebruikt/getoond.

**Comment by coemans** [comment]
We zijn bezig momenteel bezig met het toepassen van de WCAG richtlijnen. Dit issue wordt gesloten vanwege interne duplicate WCAG conform maken van al de webcomponenten.
